language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
addons:
  firefox: "41.0.1"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm i jpm
  - npm i
  - jpm test
