language: node_js
node_js:
  - "6"
addons:
  firefox: "45.2.0esr"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm i jpm
  - npm i
  - jpm test -b `which firefox`
